import type { CarProduct } from "./types";


export const productData: CarProduct[] = [
    {
        id: 1,
        name: "Mahindra Scorpio",
        price_range: { lower: 13.77, upper: 17.72 },
        rating: 4.5,
        reviews: 671,
        image_url: "scorpio",
        engine: "2.2L Diesel",
        transmission: "Manual / Automatic",
        fuel_type: "Diesel",
        power: "140 bhp",
        mileage: "16–18 kmpl",
        seating_capacity: 7,
        airbags: 6,
        boot_space: "270 L",
        isFavorite: true,
    },
    {
        id: 2,
        name: "Tata Nexon",
        price_range: { lower: 8.0, upper: 15.6 },
        rating: 4.4,
        reviews: 647,
        image_url: "nexon",
        engine: "1.5L Petrol",
        transmission: "Manual / Automatic",
        fuel_type: "Petrol",
        power: "115 bhp",
        mileage: "18–21 kmpl",
        seating_capacity: 5,
        airbags: 6,
        boot_space: "350 L",
        isFavorite: false,
    },
    {
        id: 3,
        name: "Mahindra Thar ROXX",
        price_range: { lower: 12.99, upper: 23.39 },
        rating: 4.1,
        reviews: 119,
        image_url: "thar",
        engine: "2.0L Petrol",
        transmission: "Manual / Automatic",
        fuel_type: "Petrol",
        power: "150 bhp",
        mileage: "15–17 kmpl",
        seating_capacity: 4,
        airbags: 4,
        boot_space: "251 L",
        isFavorite: false,
    },
    {
        id: 4,
        name: "Jeep Compass",
        price_range: { lower: 18.99, upper: 32.41 },
        rating: 4.5,
        reviews: 394,
        image_url: "jeep",
        engine: "2.0L Diesel",
        transmission: "Manual / Automatic",
        fuel_type: "Diesel",
        power: "170 bhp",
        mileage: "17–20 kmpl",
        seating_capacity: 5,
        airbags: 6,
        boot_space: "438 L",
        isFavorite: true,
    },
    {
        id: 5,
        name: "Mahindra XUV700",
        price_range: { lower: 14.49, upper: 25.14 },
        rating: 4.3,
        reviews: 343,
        image_url: "xuv",
        engine: "2.2L Diesel / 2.0L Petrol",
        transmission: "Manual / Automatic",
        fuel_type: "Diesel / Petrol",
        power: "155–200 bhp",
        mileage: "15–17 kmpl",
        seating_capacity: 7,
        airbags: 7,
        boot_space: "240 L",
        isFavorite: false,
    },
    {
        id: 6,
        name: "Maruti Baleno",
        price_range: { lower: 6.66, upper: 9.83 },
        rating: 4.4,
        reviews: 803,
        image_url: "baleno",
        engine: "1.2L Petrol",
        transmission: "Manual / Automatic",
        fuel_type: "Petrol",
        power: "89 bhp",
        mileage: "22–24 kmpl",
        seating_capacity: 5,
        airbags: 6,
        boot_space: "318 L",
        isFavorite: false,
    },
    {
        id: 7,
        name: "Tata Harrier EV",
        price_range: { lower: 21.49, upper: 30.59 },
        rating: 4.4,
        reviews: 1042,
        image_url: "harrier",
        engine: "—",
        transmission: "Automatic",
        fuel_type: "Electric",
        power: "170 bhp (est.)",
        mileage: "NA",
        seating_capacity: 5,
        airbags: 6,
        boot_space: "425 L",
        isFavorite: false,
    },
    {
        id: 8,
        name: "Tesla Model Y",
        price_range: { lower: 59.89, upper: 73.89 },
        rating: 4.4,
        reviews: 441,
        image_url: "tesla",
        engine: "Dual Motor Electric",
        transmission: "Automatic",
        fuel_type: "Electric",
        power: "384 bhp",
        mileage: "505 km/charge",
        seating_capacity: 5,
        airbags: 7,
        boot_space: "854 L",
        isFavorite: true,
    }
];
